/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elecciones;

import CorbaConection.ClientCorbaConection;
import javax.swing.JOptionPane;

/**
 *
 * @author Padilla_Bustamante
 */
public class Boleta extends javax.swing.JFrame {

    private String[] args;
    private String matriculaVot;

    /**
     * Creates new form Boleta
     */
    public Boleta() {
        initComponents();
        setSize(638, 900);
    }

    public Boleta(String[] args, String matricualVotante) {
        this.args = args;
        initComponents();
        this.matriculaVot = matricualVotante;
        this.candidato6.setVisible(false);
        setSize(638, 900);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        candidatos = new javax.swing.JPanel();
        candidato1 = new javax.swing.JButton();
        candidato2 = new javax.swing.JButton();
        candidato3 = new javax.swing.JButton();
        candidato4 = new javax.swing.JButton();
        candidato5 = new javax.swing.JButton();
        candidato6 = new javax.swing.JButton();
        lblMesaje = new javax.swing.JLabel();
        lblInstrucciones = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elecciones - Boleta");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        candidatos.setBackground(new java.awt.Color(204, 204, 204));
        candidatos.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        candidato1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elecciones/c1.png"))); // NOI18N
        candidato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidato1ActionPerformed(evt);
            }
        });
        candidatos.add(candidato1);

        candidato2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elecciones/c2.png"))); // NOI18N
        candidato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidato2ActionPerformed(evt);
            }
        });
        candidatos.add(candidato2);

        candidato3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elecciones/c3.png"))); // NOI18N
        candidato3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidato3ActionPerformed(evt);
            }
        });
        candidatos.add(candidato3);

        candidato4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elecciones/c4.png"))); // NOI18N
        candidato4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidato4ActionPerformed(evt);
            }
        });
        candidatos.add(candidato4);

        candidato5.setBackground(new java.awt.Color(255, 255, 255));
        candidato5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        candidato5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elecciones/c5.png"))); // NOI18N
        candidato5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidato5ActionPerformed(evt);
            }
        });
        candidatos.add(candidato5);

        candidato6.setText("jButton7");
        candidatos.add(candidato6);

        getContentPane().add(candidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 135, 560, 604));

        lblMesaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMesaje.setText("Sistema con fines educativos, ajeno a cualquier partido político. ");
        getContentPane().add(lblMesaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 790, -1, -1));

        lblInstrucciones.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblInstrucciones.setText("Seleccione el candidato de su preferencia");
        getContentPane().add(lblInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 580, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elecciones/boletaelectoral.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void candidato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidato1ActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "¿Realmente desea votar por: Ricardo Anaya Cortés?", "Confirmar voto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (op == 0) {
            ClientCorbaConection ccc = new ClientCorbaConection(this.args);
            if (ccc.votar(matriculaVot, "RicardoAnaya")) {
                JOptionPane.showMessageDialog(null, "Voto Registrado");
                this.dispose();
            }
        }
    }//GEN-LAST:event_candidato1ActionPerformed

    private void candidato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidato2ActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "¿Realmente desea votar por: José Antonio Meade?", "Confirmar voto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (op == 0) {
            ClientCorbaConection ccc = new ClientCorbaConection(this.args);
            if (ccc.votar(matriculaVot, "JoseAntonio")) {
                JOptionPane.showMessageDialog(null, "Voto Registrado");
                this.dispose();
            }
        }
    }//GEN-LAST:event_candidato2ActionPerformed

    private void candidato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidato3ActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Realmente desea votar por: Andrés Manuel López Obrador", "Confirmar voto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (op == 0) {
            ClientCorbaConection ccc = new ClientCorbaConection(this.args);
            if (ccc.votar(matriculaVot, "AndresManuel")) {
                JOptionPane.showMessageDialog(null, "Voto Registrado");
                this.dispose();
            }
        }
    }//GEN-LAST:event_candidato3ActionPerformed

    private void candidato4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidato4ActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Realmente desea votar por: Jaime Rodríguez Calderón", "Confirmar voto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (op == 0) {
            ClientCorbaConection ccc = new ClientCorbaConection(this.args);
            if (ccc.votar(matriculaVot, "Jaime")) {
                JOptionPane.showMessageDialog(null, "Voto Registrado");
                this.dispose();
            }
        }
    }//GEN-LAST:event_candidato4ActionPerformed

    private void candidato5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidato5ActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Realmente desea emitir un voto nulo", "Confirmar voto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);        
        if (op == 0) {

            ClientCorbaConection ccc = new ClientCorbaConection(this.args);
            if (ccc.votar(matriculaVot, "Nulo")) {
                JOptionPane.showMessageDialog(null, "Voto Registrado");
                this.dispose();
            }
        }
    }//GEN-LAST:event_candidato5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton candidato1;
    private javax.swing.JButton candidato2;
    private javax.swing.JButton candidato3;
    private javax.swing.JButton candidato4;
    private javax.swing.JButton candidato5;
    private javax.swing.JButton candidato6;
    private javax.swing.JPanel candidatos;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblInstrucciones;
    private javax.swing.JLabel lblMesaje;
    // End of variables declaration//GEN-END:variables
}
