/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elecciones;

import CorbaConection.ClientCorbaConection;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author Padilla_Bustamante
 */
public class Resultados extends javax.swing.JFrame {
    private String[] args;
    /**
     * Creates new form Resultados
     */
    public Resultados() {
        initComponents();
        setSize(638, 500);     
        grafica.setSize(300,300);
    }

        public Resultados(String[] args) {
        this.args=args;
        initComponents();
        setSize(638, 500);
        ArrayList<String> Candidatos = new ArrayList<String>();
        Candidatos.add("RicardoAnaya");
        Candidatos.add("JoseAntonio");
        Candidatos.add("AndresManuel");
        Candidatos.add("Jaime");
        Candidatos.add("Nulo");
        
        for (int i = 0; i < Candidatos.size(); i++) {        
        ClientCorbaConection ccc = new ClientCorbaConection(this.args);
        if(i==0){
            candidato1.setText("Ricardo Anaya Cortés"+" : "+ccc.obtenerResultados(Candidatos.get(i)));
        }
        if(i==1){
            candidato2.setText("José Antanio Meade Kuribreña"+" : "+ccc.obtenerResultados(Candidatos.get(i)));
        }
        if(i==2){
            candidato3.setText("Andrés Manuel López Obrador"+" : "+ccc.obtenerResultados(Candidatos.get(i)));
        }
        if(i==3){
            candidato4.setText("Jaime Rodríguez Calderón "+" : "+ccc.obtenerResultados(Candidatos.get(i)));
        }
        if(i==4){
            candidato5.setText("Votos nulos"+" : "+ccc.obtenerResultados(Candidatos.get(i)));
        }
        }
        
        Graphics g= grafica.getGraphics();
        
    }
        
        public void grafica()
        {
            
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        grafica = new javax.swing.JPanel();
        candidato1 = new javax.swing.JLabel();
        candidato2 = new javax.swing.JLabel();
        candidato3 = new javax.swing.JLabel();
        candidato5 = new javax.swing.JLabel();
        candidato4 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Elecciones 2018 - Resultados");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setText("Resultados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 200, 40));
        getContentPane().add(grafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 350, 350));

        candidato1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(candidato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 200, 30));

        candidato2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        candidato2.setText("jgjg");
        getContentPane().add(candidato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 200, 30));

        candidato3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        candidato3.setText("jgjg");
        getContentPane().add(candidato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 200, 30));

        candidato5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        candidato5.setText("jgjg");
        getContentPane().add(candidato5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 200, 30));

        candidato4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        candidato4.setText("jgjg");
        getContentPane().add(candidato4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 200, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elecciones/resultados.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel candidato1;
    private javax.swing.JLabel candidato2;
    private javax.swing.JLabel candidato3;
    private javax.swing.JLabel candidato4;
    private javax.swing.JLabel candidato5;
    private javax.swing.JPanel grafica;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
