package Elecciones;


/**
* Elecciones/VotosHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EleccionesInterface.idl
* martes 19 de junio de 2018 02:48:32 PM CDT
*/

abstract public class VotosHelper
{
  private static String  _id = "IDL:Elecciones/Votos:1.0";

  public static void insert (org.omg.CORBA.Any a, Elecciones.Votos that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Elecciones.Votos extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Elecciones.VotosHelper.id (), "Votos");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Elecciones.Votos read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_VotosStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Elecciones.Votos value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Elecciones.Votos narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Elecciones.Votos)
      return (Elecciones.Votos)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Elecciones._VotosStub stub = new Elecciones._VotosStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Elecciones.Votos unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Elecciones.Votos)
      return (Elecciones.Votos)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Elecciones._VotosStub stub = new Elecciones._VotosStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
