package Elecciones;


/**
* Elecciones/VotosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EleccionesInterface.idl
* martes 19 de junio de 2018 02:48:32 PM CDT
*/

public interface VotosOperations 
{
  boolean votar (String matriculaVotante, String candidato);
  boolean verificarMatricula (String matricula);
  int obtenerResultados (String candidato);
} // interface VotosOperations
