package Elecciones;

/**
* Elecciones/VotosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EleccionesInterface.idl
* martes 19 de junio de 2018 02:48:32 PM CDT
*/

public final class VotosHolder implements org.omg.CORBA.portable.Streamable
{
  public Elecciones.Votos value = null;

  public VotosHolder ()
  {
  }

  public VotosHolder (Elecciones.Votos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Elecciones.VotosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Elecciones.VotosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Elecciones.VotosHelper.type ();
  }

}
