package Elecciones;


/**
* Elecciones/Votos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EleccionesInterface.idl
* martes 19 de junio de 2018 02:48:32 PM CDT
*/

public interface Votos extends VotosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Votos
